name: 'Terraform - Azure Linux VM'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.5"

      # ===================== AZURE LOGIN =====================
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ===================== TERRAFORM INIT =====================
      - name: Terraform Init
        run: terraform init

      # ===================== VALIDATION =====================
      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # ===================== PLAN =====================
      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
        run: terraform plan -out=tfplan